ToDoList/Controllers/CongViecController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToDoList.Models;
using CaptchaMvc.HtmlHelpers;
namespace ToDoList.Controllers
{
    public class CongViecController : Controller
    {
        CongViecModel conn = new CongViecModel();
        todolistEntities todo = new todolistEntities();
        
        public ActionResult Index()
        {
            if(Session["MaNhanVien"] != null)
            {
                int id = Int32.Parse(Session["MaNhanVien"].ToString());
                ViewBag.thamgia = conn.layDSThamGia(id);
                ViewBag.all = conn.layDSCaNhan(id);
            }
            return View();
        }
        public ActionResult Create()
        {
            todolistEntities td = new todolistEntities();
            var getPhamVi = td.phamvis.ToList();
            SelectList list = new SelectList(getPhamVi, "phamvi_id", "phamvi_ten");
            ViewBag.TenPhamVi = list;
            
            return View();
        }
        [HttpPost]
        public ActionResult Create(congviec cv)
        {
            int id = Int32.Parse(Session["MaNhanVien"].ToString());
            conn.them(cv, id);
            //Response.Write("<script>alert('Thành công');</script>");
            TempData["ThemThanhCong"] = "Thêm thành công.";
            return RedirectToAction(nameof(Create));
            
        }
        public ActionResult Edit(int id)
        {
            todolistEntities td = new todolistEntities();
            ViewBag.cv = conn.layCV(id);
            var getPhamVi = td.phamvis.ToList();
            SelectList list = new SelectList(getPhamVi, "phamvi_id", "phamvi_ten");
            ViewBag.TenPhamVi = list;
            return View(conn.layCV(id));
        }
        [HttpPost]
        public ActionResult Edit(congviec cv)
        {
            conn.sua(cv);
            TempData["SuaThanhCong"] = "Sửa thành công.";
            if (Int32.Parse(Session["MaChucVu"].ToString()) == 1)
            {
                return RedirectToAction(nameof(Edit));
                //return RedirectToAction("NhanVien/Index");//load lại trang
            }
            return RedirectToAction("Index");
            
        }
        public ActionResult Delete(int id)
        {
            conn.xoa(id);
            TempData["XoaThanhCong"] = "Xóa thành công.";
            //return RedirectToAction("Index");
            //return Redirect(Request.UrlReferrer.ToString());
            return Redirect(Request.UrlReferrer.ToString());//load lại trang
        }
        public ActionResult HoanThanh(int id)
        {

            congviec cv = conn.layCV(id);

            congviec c = new congviec();
            c.congviec_id = cv.congviec_id;
            c.congviec_ten = cv.congviec_ten;
            c.congviec_ngaybatdau = cv.congviec_ngaybatdau;
            c.congviec_ngayketthuc = cv.congviec_ngayketthuc;
            c.congviec_ngayhoanthanh = DateTime.Now;
            c.phamvi_id = cv.phamvi_id;
            conn.sua(c);
            TempData["HoanThanh"] = "Hoàn thành thành công.";
            return RedirectToAction("Index");
        }
        public ActionResult CongViecHoanThanh()
        {
            if (Session["MaNhanVien"] != null)
            {
                int id = Int32.Parse(Session["MaNhanVien"].ToString());
                ViewBag.dunghan = conn.layDSDungHan(id);
                ViewBag.trehan = conn.layDSTreHan(id);
            }
            
            return View();
        }

        //------------------------------------------------------------------
        
        public ActionResult XoaNguoiLam(int id)
        {
            conn.XoaNguoiLam(id);
            TempData["XoaThanhCong"] = "Xóa thành công.";
            //return RedirectToAction("ThemNguoiLam");
            return Redirect(Request.UrlReferrer.ToString());//load lại trang
        }
        
        

        public ActionResult ThemNguoiLam(int id)
        {
            var dsNguoiLam = (from s in todo.nhanvien_congviec
                              
                              where s.congviec_id == id
                              select s).ToList();
            ViewBag.dsNguoiLam = dsNguoiLam;

            var congViec  = (from p in todo.congviecs
                             where p.congviec_id == id
                             select p).ToList();
            SelectList ds = new SelectList(congViec, "congviec_id", "congviec_ten");
            ViewBag.TenCongViec = ds;

            
            var nguoiLam = (from p in todo.nhanviens
                            select p).ToList();
            SelectList list = new SelectList(nguoiLam, "nhanvien_id", "nhanvien_ten");
            ViewBag.TenNguoiLam = list;

            var quyen = (from p in todo.quyens
                            where p.quyen_id == 2
                            select p).ToList();
            SelectList tenQuyen = new SelectList(quyen, "quyen_id", "quyen_ten");
            ViewBag.TenQuyen = tenQuyen;
            return View();
        }
        [HttpPost]
        public ActionResult ThemNguoiLam(nhanvien_congviec cv)
        {
            conn.themNguoiLam(cv);
            TempData["ThemThanhCong"] = "Thêm thành công.";
            return RedirectToAction("ThemNguoiLam");
        }

        [HttpPost]
        public ActionResult TimKiemCV(string searchString)
        {
            ViewBag.TuKhoa = searchString;
            if (Session["MaNhanVien"] != null)
            {
                
                int id = Int32.Parse(Session["MaNhanVien"].ToString());
                /*
                var cv = (from c in todo.congviecs
                         join n in todo.nhanvien_congviec on c.congviec_id equals n.congviec_id
                         where n.nhanvien_id == id
                     select c);
                if (!String.IsNullOrEmpty(searchString)) // kiểm tra chuỗi tìm kiếm có rỗng/null hay không
                {
                    cv = cv.Where(c => c.congviec_ten.Contains(searchString)); //lọc theo chuỗi tìm kiếm
                }
                */
                ViewBag.CV = conn.TimKiemCV(searchString, id);
            }

            TempData["tim"] = "Welcome back!";
            return View();
        }
        
    }


}

ToDoList/Controllers/NhanVienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class NhanVienController : Controller
    {
        NhanVienModel conn = new NhanVienModel();
        CongViecModel cvModel = new CongViecModel();
        todolistEntities todo = new todolistEntities();
        public ActionResult Index()
        {
            int id = Int32.Parse(Session["MaNhanVien"].ToString());
            ViewBag.DSNV = conn.layDSNV();
            ViewBag.NV = conn.layNhanVien(id);
            return View();
        }
        public ActionResult ThemNhanVien()
        {
            var getChucVu = todo.chucvus.ToList();
            SelectList list = new SelectList(getChucVu, "chucvu_id", "chucvu_ten");
            ViewBag.TenChucVu = list;
            return View();
        }
        [HttpPost]
        public ActionResult ThemNhanVien(nhanvien nv)
        {
            conn.themNhanVien(nv);
            TempData["ThemThanhCong"] = "Thêm thành công.";
            return RedirectToAction("ThemNhanVien");
        }
        public ActionResult SuaNhanVien(int id)
        {
            var getChucVu = todo.chucvus.ToList();
            SelectList list = new SelectList(getChucVu, "chucvu_id", "chucvu_ten");
            ViewBag.TenChucVu = list;
            return View(conn.layNhanVien(id));
        }
        [HttpPost]
        public ActionResult SuaNhanVien(nhanvien nv)
        {
            conn.suaNhanVien(nv);
            TempData["SuaThanhCong"] = "Sửa thành công.";
            //return Redirect(Request.UrlReferrer.ToString());//load lại trang
            return RedirectToAction("Index");
        }
        public ActionResult XoaNhanVien(int id)
        {
            conn.xoaNhanVien(id);
            TempData["XoaThanhCong"] = "Xóa thành công.";
            return RedirectToAction("Index");
        }
        public ActionResult XemCVNhanVien(int id)
        {
            ViewBag.CVTuTao = cvModel.layDSCaNhan(id);
            ViewBag.CVThamGia = cvModel.layDSThamGia(id);
            ViewBag.CVTreHan = cvModel.layDSTreHan(id);
            ViewBag.CVDungHan = cvModel.layDSDungHan(id);
            return View();
        }
        [HttpPost]
        public ActionResult TimKiemNV(string searchString)
        {
            ViewBag.TuKhoa = searchString;
            /*
            var cv = (from c in todo.nhanviens
                        select c);
            if (!String.IsNullOrEmpty(searchString)) // kiểm tra chuỗi tìm kiếm có rỗng/null hay không
            {
                cv = cv.Where(c => c.nhanvien_ten.Contains(searchString)); //lọc theo chuỗi tìm kiếm
            }
            */
            ViewBag.NV = conn.TimKiemNV(searchString);

            return View();
        }
        public ActionResult Login()
        {
            ViewBag.Message = TempData["message"];

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(nhanvien model)
        {

            if (ModelState.IsValid)
            {
                var data = conn.Login(model);
                if (data.Count() > 0)
                {
                    //add session
                    Session["MaNhanVien"] = data.FirstOrDefault().nhanvien_id;
                    Session["TenNhanVien"] = data.FirstOrDefault().nhanvien_ten;
                    Session["MaChucVu"] = data.FirstOrDefault().chucvu_id;
                    //Session["TenDangNhap"] = data.FirstOrDefault().taikhoan;
                    foreach (var item in data)
                    {
                        if (item.chucvu_id == 1)
                        {
                            //return RedirectToAction("Index");
                            return Redirect("NhanVien/Index");
                        }
                        else
                        {
                            //return RedirectToAction("Index");
                            return Redirect("CongViec/Index");
                        }
                    }

                }
                else
                {
                    TempData["message"] = "Tên đăng hoặc mật khẩu không chính xác.";
                    ViewBag.mes = "Tên đăng nhập hoặc mật khẩu không chính xác.";
                    return RedirectToAction("Login");
                }
            }
            return View();
        }


        //Logout
        public ActionResult Logout()
        {
            Session.Clear();//remove session
            return RedirectToAction("Login");
        }
        public ActionResult StaffInFo(int id)
        {

            ViewBag.TT = conn.layThongTinNV(id);
            return View(conn.layThongTinNV(id));
        }
        [HttpPost]
        public ActionResult StaffInFo(nhanvien nv)
        {
            //nhanvien n = new nhanvien();

            conn.suaNhanVien(nv);
            TempData["SuaThanhCong"] = "Sửa thành công.";
            return Redirect(Request.UrlReferrer.ToString());//load lại trang
            //return RedirectToAction("Index");
        }
    }
}

ToDoList/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ToDoList.Controllers
{
    public class TestController : Controller
    {
        // GET: Test
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult LoadAjax(int a, int b)
        {
            return Content((a + b).ToString());
        }
    }
}

ToDoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("css", false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Trang chủ", "Index", "CongViec", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Thêm công việc", "Create", "CongViec")</li>
                    <li>@Html.ActionLink("Công việc đã hoàn thành", "CongViecHoanThanh", "CongViec")</li>
                    @if (Session["TenNhanVien"] != null)
                    {
                        <li>@Session["TenNhanVien"].ToString()</li>
                        <li><a href="@Url.Action("Logout","CongViec")" class="btn btn-warning">Logout</a></li>
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ToDoList/Views/Shared/_LayoutCustomize.cshtml
@{

    Layout = null;
    
}

<!doctype html>
<html lang="en">

<head>
    <title>Todo List</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="/assets/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/vendor/linearicons/style.css">
    <link rel="stylesheet" href="/assets/vendor/chartist/css/chartist-custom.css">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="/assets/css/main.css">
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="/assets/css/demo.css">
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <!-- ICONS -->
    <link rel="apple-touch-icon" sizes="76x76" href="/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/assets/img/favicon.png">
</head>

<body>
    <!-- WRAPPER -->
    <div id="wrapper">
        <!-- NAVBAR -->
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="brand">
                <a href=""><img src="/assets/img/logo-dark.png" alt="Klorofil Logo" class="img-responsive logo"></a>
            </div>
            <div class="container-fluid">
                <div class="navbar-btn">
                    <button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
                </div>
                @if (Session["MaChucVu"] != null)
                {
                    if (Int32.Parse(Session["MaChucVu"].ToString()) == 1)
                    {
                        
                        <form class="navbar-form navbar-left" method="post" action="/NhanVien/TimKiemNV">
                            <div class="input-group">
                                <input type="text" value="" class="form-control" placeholder="Nhập từ khóa..." name="searchString"  required pattern="\S+.*">
                                <span class="input-group-btn"><button type="submit" class="btn btn-primary">Tìm kiếm</button></span>
                            </div>
                        </form>
                    }
                    else
                    {
                        <form class="navbar-form navbar-left" method="post" action="/CongViec/TimKiemCV">
                            <div class="input-group">
                                <input type="text" value="" class="form-control" placeholder="Nhập từ khóa..." name="searchString"  required pattern="\S+.*">
                                <span class="input-group-btn"><button type="submit" class="btn btn-primary" onclick="return toastr.success('Tìm','Toastr');">Tìm kiếm</button></span>
                            </div>
                        </form>
                    }
                }
                
                
                <div id="navbar-menu">
                    <ul class="nav navbar-nav navbar-right">
                        
                        
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="~/assets/img/user.png" class="img-circle" alt="Avatar"> <span>@if (Session["TenNhanVien"] != null){@Session["TenNhanVien"].ToString()}</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                            <ul class="dropdown-menu">
                                <li><a href=""><i class="lnr lnr-user"></i><span>Thông tin cá nhân</span></a></li>
                                <!---<li><a href="#"><i class="lnr lnr-envelope"></i> <span>Message</span></a></li>
                                <li><a href="#"><i class="lnr lnr-cog"></i> <span>Settings</span></a></li>--->
                                <li><a href="@Url.Action("Logout","NhanVien")" onclick = "return confirm('Đăng xuất?');"><i class="lnr lnr-exit"></i> <span>Đăng xuất</span></a></li>
                            </ul>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
        <!-- END NAVBAR -->
        <!-- LEFT SIDEBAR -->
        <div id="sidebar-nav" class="sidebar">
            <div class="sidebar-scroll">
                <nav>
                    <ul class="nav">
                        @if(Session["MaChucVu"] != null)
                        {
                            int id = Int32.Parse(Session["MaChucVu"].ToString());
                            if (id == 1)
                            {
                                <li>@Html.ActionLink(" Danh sách nhân viên", "Index", "NhanVien")</li>
                                <li>@Html.ActionLink(" Thêm nhân viên", "ThemNhanVien", "NhanVien")</li>
                                <li>@Html.ActionLink("Tạo công việc", "Create", "CongViec")</li>
                            }
                            else
                            {
                                <li>@Html.ActionLink(" Trang chủ", "Index", "CongViec")</li>
                                <li>@Html.ActionLink(" Thêm công việc", "Create", "CongViec")</li>
                                <li>@Html.ActionLink("Công việc đã hoàn thành", "CongViecHoanThanh", "CongViec")</li>
                            }
                        }

                        <!---
    <li><a href="~/Views/CongViec/Index.cshtml" class="active"><i class="lnr lnr-home"></i> <span>Trang chủ</span></a></li>
    <li><a href="~/Views/CongViec/Create.cshtml" class=""><i class="lnr lnr-code"></i> <span>Thêm công việc</span></a></li>
    <li><a href="~/Views/CongViec/CongViecHoanThanh.cshtml" class=""><i class="lnr lnr-chart-bars"></i> <span>Công việc hoàn thành</span></a></li>
    <li><a href="panels.html" class=""><i class="lnr lnr-cog"></i> <span>Panels</span></a></li>
    <li><a href="notifications.html" class=""><i class="lnr lnr-alarm"></i> <span>Notifications</span></a></li>

    <li>
        <a href="#subPages" data-toggle="collapse" class="collapsed"><i class="lnr lnr-file-empty"></i> <span>Pages</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
        <div id="subPages" class="collapse ">
            <ul class="nav">
                <li><a href="page-profile.html" class="">Profile</a></li>
                <li><a href="page-login.html" class="">Login</a></li>
                <li><a href="page-lockscreen.html" class="">Lockscreen</a></li>
            </ul>
        </div>
    </li>
    <li><a href="tables.html" class=""><i class="lnr lnr-dice"></i> <span>Tables</span></a></li>
    <li><a href="icons.html" class=""><i class="lnr lnr-linearicons"></i> <span>Icons</span></a></li>
    --->
                    </ul>
                </nav>
            </div>
        </div>
        <!-- END LEFT SIDEBAR -->
        <!-- MAIN -->
        <div class="main">
            <!-- MAIN CONTENT -->
            <div class="main-content">
                <div class="container-fluid">
                    @RenderBody()
                    
                </div>
            </div>
            <!-- END MAIN CONTENT -->
        </div>
        <!-- END MAIN -->
        <div class="clearfix"></div>
        <footer>
            <div class="container-fluid">
                <p class="copyright">&copy; 2017 <a href="https://www.themeineed.com" target="_blank">Theme I Need</a>. All Rights Reserved.</p>
            </div>
        </footer>
    </div>
    <!-- END WRAPPER -->
    <!-- Javascript -->
    <script src="/assets/vendor/jquery/jquery.min.js"></script>
    <script src="/assets/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="/assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script src="/assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
    <script src="/assets/vendor/chartist/js/chartist.min.js"></script>
    <script src="/assets/scripts/klorofil-common.js"></script>
    <script src="~/assets/vendor/toastr/toastr.js"></script>
    <script>
        $(function () {
            var data, options;

            // headline charts
            data = {
                labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
                series: [
                    [23, 29, 24, 40, 25, 24, 35],
                    [14, 25, 18, 34, 29, 38, 44],
                ]
            };

            options = {
                height: 300,
                showArea: true,
                showLine: false,
                showPoint: false,
                fullWidth: true,
                axisX: {
                    showGrid: false
                },
                lineSmooth: false,
            };

            new Chartist.Line('#headline-chart', data, options);


            // visits trend charts
            data = {
                labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                series: [{
                    name: 'series-real',
                    data: [200, 380, 350, 320, 410, 450, 570, 400, 555, 620, 750, 900],
                }, {
                    name: 'series-projection',
                    data: [240, 350, 360, 380, 400, 450, 480, 523, 555, 600, 700, 800],
                }]
            };

            options = {
                fullWidth: true,
                lineSmooth: false,
                height: "270px",
                low: 0,
                high: 'auto',
                series: {
                    'series-projection': {
                        showArea: true,
                        showPoint: false,
                        showLine: false
                    },
                },
                axisX: {
                    showGrid: false,

                },
                axisY: {
                    showGrid: false,
                    onlyInteger: true,
                    offset: 0,
                },
                chartPadding: {
                    left: 20,
                    right: 20
                }
            };

            new Chartist.Line('#visits-trends-chart', data, options);


            // visits chart
            data = {
                labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
                series: [
                    [6384, 6342, 5437, 2764, 3958, 5068, 7654]
                ]
            };

            options = {
                height: 300,
                axisX: {
                    showGrid: false
                },
            };

            new Chartist.Bar('#visits-chart', data, options);


            // real-time pie chart
            var sysLoad = $('#system-load').easyPieChart({
                size: 130,
                barColor: function (percent) {
                    return "rgb(" + Math.round(200 * percent / 100) + ", " + Math.round(200 * (1.1 - percent / 100)) + ", 0)";
                },
                trackColor: 'rgba(245, 245, 245, 0.8)',
                scaleColor: false,
                lineWidth: 5,
                lineCap: "square",
                animate: 800
            });

            var updateInterval = 3000; // in milliseconds

            setInterval(function () {
                var randomVal;
                randomVal = getRandomInt(0, 100);

                sysLoad.data('easyPieChart').update(randomVal);
                sysLoad.find('.percent').text(randomVal);
            }, updateInterval);

            function getRandomInt(min, max) {
                return Math.floor(Math.random() * (max - min + 1)) + min;
            }

        });
    </script>
    
    <script>
        $(document).ready(function () {
            $('.hide').hide();
        });
    </script>
    <script>
        document.getElementById('date').valueAsDate = new Date();
    </script>
    <script>
        if (@ViewBag.ThanhCong!= null) {
            alert('hi');
        }
    </script>
    <script>
        function NullMessage() {
            document.getElementById('loginMessage').innerHTML = "";
        }
    </script>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    </body>

</html>

ToDoList/Views/Shared/_LayoutLogin.cshtml
@{
    Layout = null;
}

<!doctype html>
<html lang="en" class="fullscreen-bg">

<head>
    <title>Login | Klorofil - Free Bootstrap Dashboard Template</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/vendor/linearicons/style.css">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="/assets/css/main.css">
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="/assets/css/demo.css">
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <!-- ICONS -->
    <link rel="apple-touch-icon" sizes="76x76" href="/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/assets/img/favicon.png">
</head>

<body>
    <!-- WRAPPER -->
    <div id="wrapper">
        <div class="vertical-align-wrap">
            <div class="vertical-align-middle">
                <div class="auth-box ">
                    <div class="left">
                        <div class="content">
                            <div class="header">
                                <div class="logo text-center"><img src="/assets/img/logo-dark.png" alt="Klorofil Logo"></div>
                                <p class="lead">Login to your account</p>
                            </div>
                            <!--
                            <form class="form-auth-small" action="index.php">
                                <div class="form-group">
                                    <label for="signin-email" class="control-label sr-only">Email</label>
                                    <input type="email" class="form-control" id="signin-email" value="samuel.gold@domain.com" placeholder="Email">
                                </div>
                                <div class="form-group">
                                    <label for="signin-password" class="control-label sr-only">Password</label>
                                    <input type="password" class="form-control" id="signin-password" value="thisisthepassword" placeholder="Password">
                                </div>
                                <div class="form-group clearfix">
                                    <label class="fancy-checkbox element-left">
                                        <input type="checkbox">
                                        <span>Remember me</span>
                                    </label>
                                </div>
                                <button type="submit" class="btn btn-primary btn-lg btn-block">LOGIN</button>
                                <div class="bottom">
                                    <span class="helper-text"><i class="fa fa-lock"></i> <a href="#">Forgot password?</a></span>
                                </div>
                            </form>
                                --->
                            @RenderBody()
                        </div>
                    </div>
                    <div class="right">
                        <div class="overlay"></div>
                        <div class="content text">
                            <h1 class="heading">Free Bootstrap dashboard template</h1>
                            <p>by The Develovers</p>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
    <!-- END WRAPPER -->
    @if (TempData["message"] != null)
    {
        <script>toastr.error('Đăng nhập thất bại.');</script>
    }
</body>

</html>